const USER_TYPE = ["Agency Partner", "Corporate Donor", "Public Donor"];

export const userDataMock = [
  {
    firstName: "NEW",
    lastName: "USER1",
    email: "john.doe1@example.com",
    userType: USER_TYPE[0],
    organizationId: 1,
    hash: "hashed_password",
    salt: "random_salt",
    phone: "1234567890",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    household: "abc",
    status: "Active",
  },
  {
    firstName: "NEW",
    lastName: "USER2",
    email: "john.doe2@example.com",
    userType: USER_TYPE[0],
    hash: "hashed_password",
    salt: "random_salt",
    phone: "1234567890",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Active",
    household: "abc",
  },
  {
    firstName: "NEW3",
    lastName: "USER3",
    email: "john.doe3@example.com",
    userType: USER_TYPE[0],
    organizationId: 1,
    hash: "hashed_password3",
    salt: "random_salt3",
    phone: "1234567893",
    address: "323 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12348,
    status: "Active",
    household: "abc3",
  },
  {
    firstName: "NEW4",
    lastName: "USER4",
    email: "john.doe4@example.com",
    userType: USER_TYPE[0],
    organizationId: 1,
    hash: "hashed_password4",
    salt: "random_salt4",
    phone: "1234567894",
    address: "423 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12349,
    status: "Inactive",
    household: "abc4",
  },
  {
    firstName: "NEW5",
    lastName: "USER5",
    email: "john.doe5@example.com",
    userType: USER_TYPE[1],
    organizationId: 1,
    hash: "hashed_password5",
    salt: "random_salt5",
    phone: "1234567895",
    address: "523 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12350,
    status: "Inactive",
    household: "abc5",
  },
  {
    firstName: "NEW6",
    lastName: "USER6",
    email: "john.doe6@example.com",
    userType: USER_TYPE[1],
    organizationId: 1,
    hash: "hashed_password6",
    salt: "random_salt6",
    phone: "1234567896",
    address: "623 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12351,
    status: "Inactive",
    household: "abc6",
  },
  {
    firstName: "NEW7",
    lastName: "USER7",
    email: "john.doe7@example.com",
    userType: USER_TYPE[1],
    organizationId: 1,
    hash: "hashed_password7",
    salt: "random_salt7",
    phone: "1234567897",
    address: "723 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12352,
    status: "Inactive",
    household: "abc7",
  },
  {
    firstName: "NEW8",
    lastName: "USER8",
    email: "john.doe8@example.com",
    userType: USER_TYPE[0],
    organizationId: 1,
    hash: "hashed_password8",
    salt: "random_salt8",
    phone: "1234567898",
    address: "823 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12353,
    status: "Active",
    household: "abc8",
  },
  {
    firstName: "NEW9",
    lastName: "USER9",
    email: "john.doe9@example.com",
    userType: USER_TYPE[1],
    organizationId: 1,
    hash: "hashed_password9",
    salt: "random_salt9",
    phone: "1234567898",
    address: "823 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12353,
    status: "Active",
    household: "abc9",
  },
  {
    firstName: "NEW",
    lastName: "USER10",
    email: "john.doe10@example.com",
    userType: USER_TYPE[1],
    organizationId: 1,
    hash: "hashed_password10",
    salt: "random_salt10",
    phone: "1234567890",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Active",
    household: "abc10",
  },
  {
    firstName: "NEW",
    lastName: "USER11",
    email: "john.doe11@example.com",
    userType: USER_TYPE[2],
    organizationId: 1,
    hash: "hashed_password11",
    salt: "random_salt11",
    phone: "1234567891",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Active",
    household: "abc11",
  },
  {
    firstName: "NEW",
    lastName: "USER12",
    email: "john.doe12@example.com",
    userType: USER_TYPE[2],
    organizationId: 1,
    hash: "hashed_password12",
    salt: "random_salt12",
    phone: "1234567892",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Active",
    household: "abc12",
  },
  {
    firstName: "NEW",
    lastName: "USER13",
    email: "john.doe13@example.com",
    userType: USER_TYPE[2],
    organizationId: 1,
    hash: "hashed_password13",
    salt: "random_salt13",
    phone: "1234567893",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Active",
    household: "abc13",
  },
  {
    firstName: "NEW",
    lastName: "USER14",
    email: "john.doe14@example.com",
    userType: USER_TYPE[2],
    organizationId: 1,
    hash: "hashed_password14",
    salt: "random_salt14",
    phone: "1234567894",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Active",
    household: "abc14",
  },
  {
    firstName: "NEW",
    lastName: "USER15",
    email: "john.doe15@example.com",
    userType: USER_TYPE[2],
    organizationId: 1,
    hash: "hashed_password15",
    salt: "random_salt15",
    phone: "1234567895",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Active",
    household: "abc15",
  },
  {
    firstName: "NEW",
    lastName: "USER16",
    email: "john.doe16@example.com",
    userType: USER_TYPE[0],
    organizationId: 1,
    hash: "hashed_password16",
    salt: "random_salt16",
    phone: "1234567895",
    address: "123 Main St",
    city: "Anytown",
    state: "Anystate",
    zip: 12345,
    status: "Inactive",
    household: "abc16",
  },
];

export const itemDataMock = [
  {
    category: "Books",
    name: "Science Fiction Novel",
    quantityUsed: 12,
    quantityNew: 7,
    valueUsed: 3.0,
    valueNew: 6.0,
  },
  {
    category: "Books",
    name: "Cooking Recipes",
    quantityUsed: 8,
    quantityNew: 9,
    valueUsed: 2.0,
    valueNew: 4.5,
  },
  {
    category: "Clothes",
    name: "Jeans",
    quantityUsed: 15,
    quantityNew: 5,
    valueUsed: 2.0,
    valueNew: 4.0,
  },
  {
    category: "Clothes",
    name: "Sweater",
    quantityUsed: 10,
    quantityNew: 8,
    valueUsed: 2.5,
    valueNew: 5.0,
  },
  {
    category: "Books",
    name: "Mystery Thriller",
    quantityUsed: 5,
    quantityNew: 10,
    valueUsed: 3.5,
    valueNew: 7.0,
  },
  {
    category: "Clothes",
    name: "Winter Jacket",
    quantityUsed: 7,
    quantityNew: 3,
    valueUsed: 5.0,
    valueNew: 10.0,
  },
  {
    category: "Books",
    name: "Historical Fiction",
    quantityUsed: 11,
    quantityNew: 6,
    valueUsed: 2.5,
    valueNew: 5.5,
  },
  {
    category: "Clothes",
    name: "Running Shoes",
    quantityUsed: 14,
    quantityNew: 7,
    valueUsed: 3.0,
    valueNew: 6.0,
  },
  {
    category: "Books",
    name: "Biography of a Scientist",
    quantityUsed: 9,
    quantityNew: 4,
    valueUsed: 4.0,
    valueNew: 8.0,
  },
  {
    category: "Clothes",
    name: "Baseball Cap",
    quantityUsed: 18,
    quantityNew: 9,
    valueUsed: 1.0,
    valueNew: 2.0,
  },
];

export const organizationData = [
  {
    name: "Public",
    type: "Public",
  },
  {
    name: "Target",
    type: "Corporate",
  },
  {
    name: "Walmart",
    type: "Corporate",
  },
  {
    name: "Amazon",
    type: "Corporate",
  },
  {
    name: "Helping Hands",
    type: "Agency",
  },
  {
    name: "Baby To Baby",
    type: "Agency",
  },
  {
    name: "Goodwill",
    type: "Agency",
  },
  {
    name: "Salvation Army",
    type: "Agency",
  },
  {
    name: "Red Cross",
    type: "Agency",
  },
  {
    name: "Habitat for Humanity",
    type: "Agency",
  },
];

export const adminDataMock = [
  {
    name: "NEW ADMIN1",
    email: "john.doe1@example.com",
    role: "Human Resources",
  },
  {
    name: "NEW ADMIN2",
    email: "john.doe2@example.com",
    role: "Operations",
  },
  {
    name: "NEW ADMIN3",
    email: "john.doe3@example.com",
    role: "Fundraising",
  },
];
